/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_fanchen_aisou_jni_HostURL.h"
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getBookUrl
  (JNIEnv *env, jclass jc, jint ji){
	jstring str ;
		switch (ji) {
		case 0:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.cn/modules/article/search.php?searchtype=articlename&searchkey=");
			break;
		case 1:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.com/modules/article/toplist.php?sort=lastupdate&page=");
			break;
		case 2:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.com/modules/article/articlelist.php?page=");
			break;
		case 3:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.com/modules/article/toplist.php?sort=anime&page=");
			break;
		case 4:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.com/modules/article/toplist.php?sort=allvisit&page=");
			break;
		case 5:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.com/modules/article/toplist.php?sort=postdate&page=");
			break;
		case 6:
			str = (*env)->NewStringUTF(env, "http://www.wenku8.com/modules/article/articlelist.php?fullflag=1&page=");
			break;
		default:
			break;
		}
		return str;
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getSearchUrl
  (JNIEnv *env, jclass jc, jint ji) {
	jstring str ;
	switch (ji) {
	case 0:
		str = (*env)->NewStringUTF(env, "http://www.wangpansou.cn/s.php?");
		break;
	case 1:
		str = (*env)->NewStringUTF(env, "http://www.cilisou.cn/s.php?q=");
		break;
	default:
		break;
	}
	return str;
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getImageUrl
  (JNIEnv *env, jclass jc){
	return  (*env)->NewStringUTF(env, "http://image.baidu.com/channel/listjson?rn=30&tag1=%E5%8A%A8%E6%BC%AB&tag2=%E5%8A%A8%E6%BC%AB%E7%BE%8E%E5%B0%91%E5%A5%B3&ie=utf8&pn=");
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getHotWordUrl
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "http://www.7060.la/paihang/");
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getShareUrl
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "http://android.myapp.com/myapp/detail.htm?apkName=com.fanchen.aisou");
}
