/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanchen_aisou_jni_BmobValue */

#ifndef _Included_com_fanchen_aisou_jni_BmobValue
#define _Included_com_fanchen_aisou_jni_BmobValue
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanchen_aisou_jni_BmobValue
 * Method:    getAccessKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getAccessKey
  (JNIEnv *, jclass);

/*
 * Class:     com_fanchen_aisou_jni_BmobValue
 * Method:    getApplicationID
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getApplicationID
  (JNIEnv *, jclass);

/*
 * Class:     com_fanchen_aisou_jni_BmobValue
 * Method:    getRESTAPIKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getRESTAPIKey
  (JNIEnv *, jclass);

/*
 * Class:     com_fanchen_aisou_jni_BmobValue
 * Method:    getMasterKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getMasterKey
  (JNIEnv *, jclass);

/*
 * Class:     com_fanchen_aisou_jni_BmobValue
 * Method:    getSecretKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getSecretKey
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
