/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fanchen_aisou_jni_HostURL */

#ifndef _Included_com_fanchen_aisou_jni_HostURL
#define _Included_com_fanchen_aisou_jni_HostURL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fanchen_aisou_jni_HostURL
 * Method:    getBookUrl
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getBookUrl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fanchen_aisou_jni_HostURL
 * Method:    getSearchUrl
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getSearchUrl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_fanchen_aisou_jni_HostURL
 * Method:    getImageUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getImageUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_fanchen_aisou_jni_HostURL
 * Method:    getHotWordUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getHotWordUrl
  (JNIEnv *, jclass);

/*
 * Class:     com_fanchen_aisou_jni_HostURL
 * Method:    getShareUrl
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_HostURL_getShareUrl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
