/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "com_fanchen_aisou_jni_BmobValue.h"
/* Header for class com_fanchen_aisou_jni_BmobValue */

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getAccessKey
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "eca38a74461dc4371b877e26f703dc5f");
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getApplicationID
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "788a47ac80714e85d730276a75f018d5");
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getRESTAPIKey
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "0fae6e95fed71dc53eebfe47b70157c5");
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getMasterKey
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "1371a3520321ca50cbb9d4bedc019330");
}

JNIEXPORT jstring JNICALL Java_com_fanchen_aisou_jni_BmobValue_getSecretKey
  (JNIEnv *env, jclass jc){
	return (*env)->NewStringUTF(env, "94f0d07d1343dfc6");
}

